<?php

use Illuminate\Database\Seeder;

class NacionalidadesTableSeeder extends DatabaseSeeder {

	/**
     * Run the database seeds.
     *
     * @return void
     */
 public function run()
    {
        DB::table('nacionalidade')->delete();
        DB::table("nacionalidade")->insert([
   
 	 	 	   ['id'=> 1, 'nacionalidade'=>'Afegã'],
  	 	 	 ['id'=> 2, 'nacionalidade'=>'Albanêsa'],
         ['id'=> 3, 'nacionalidade'=>'Alemã'],
  	 	 	 ['id'=> 4, 'nacionalidade'=>'Argelina'],
  	 	 	 ['id'=> 5, 'nacionalidade'=>'Americana'],
  	 	 	 ['id'=> 6, 'nacionalidade'=>'Andorrana'],
  	 	 	 ['id'=> 7, 'nacionalidade'=>'Angolana'],
  	 	 	 ['id'=> 8, 'nacionalidade'=>'Antiguans'],
  	 	 	 ['id'=> 9, 'nacionalidade'=>'Argentina'],
  	 	 	 ['id'=> 10, 'nacionalidade'=>'Armêna'],
  	 	 	 ['id'=> 11, 'nacionalidade'=>'Australiana'],
  	 	 	 ['id'=> 12, 'nacionalidade'=>'Austriaca'],
  	 	 	 ['id'=> 13, 'nacionalidade'=>'Azerbaijanêsa'],
  	 	 	 ['id'=> 14, 'nacionalidade'=>'Bahamense'],
  	 	 	 ['id'=> 15, 'nacionalidade'=>'Bahrein'],
  	 	 	 ['id'=> 16, 'nacionalidade'=>'Bangladeshi'],
  	 	 	 ['id'=> 17, 'nacionalidade'=>'Barbadense'],
  	 	 	 ['id'=> 18, 'nacionalidade'=>'Barbudans'],
  	 	 	 ['id'=> 19, 'nacionalidade'=>'Batswana'],
  	 	 	 ['id'=> 20, 'nacionalidade'=>'Bielorrussa'],
  	 	 	 ['id'=> 21, 'nacionalidade'=>'Belga'],
  	 	 	 ['id'=> 22, 'nacionalidade'=>'Belizean'],
  	 	 	 ['id'=> 23, 'nacionalidade'=>'Beninêsa'],
  	 	 	 ['id'=> 24, 'nacionalidade'=>'Butanêsa'],
  	 	 	 ['id'=> 25, 'nacionalidade'=>'Boliviana'],
  	 	 	 ['id'=> 26, 'nacionalidade'=>'Bósnia'],
  	 	 	 ['id'=> 27, 'nacionalidade'=>'Brasileira'],
  	 	 	 ['id'=> 28, 'nacionalidade'=>'Britanica'],
  	 	 	 ['id'=> 29, 'nacionalidade'=>'Bruneian'],
  	 	 	 ['id'=> 30, 'nacionalidade'=>'Búlgara'],
  	 	 	 ['id'=> 31, 'nacionalidade'=>'Burkinabe'],
  	 	 	 ['id'=> 32, 'nacionalidade'=>'Birmanêsa'],
  	 	 	 ['id'=> 33, 'nacionalidade'=>'Burundiana'],
  	 	 	 ['id'=> 34, 'nacionalidade'=>'Cambojana'],
  	 	 	 ['id'=> 35, 'nacionalidade'=>'Camaronêsa'],
  	 	 	 ['id'=> 36, 'nacionalidade'=>'Canadense'],
  	 	 	 ['id'=> 37, 'nacionalidade'=>'Cabo verdiana'],
         ['id'=> 38, 'nacionalidade'=>'Cazaquistã'],
  	 	 	 ['id'=> 39, 'nacionalidade'=>'Central Africana'],
         ['id'=> 40, 'nacionalidade'=>'Cingapurense'],
  	 	 	 ['id'=> 41, 'nacionalidade'=>'Chadiana'],
  	 	 	 ['id'=> 42, 'nacionalidade'=>'Chilena'],
  	 	 	 ['id'=> 43, 'nacionalidade'=>'Chinesa'],
  	 	 	 ['id'=> 44, 'nacionalidade'=>'Colombiana'],
  	 	 	 ['id'=> 45, 'nacionalidade'=>'Comoran'],
  	 	 	 ['id'=> 46, 'nacionalidade'=>'Congolêsa'],
  	 	 	 ['id'=> 47, 'nacionalidade'=>'Costa riquenha'],
  	 	 	 ['id'=> 48, 'nacionalidade'=>'Croata'],
  	 	 	 ['id'=> 49, 'nacionalidade'=>'Cubana'],
  	 	 	 ['id'=> 50, 'nacionalidade'=>'Cipriota'],
  	 	 	 ['id'=> 51, 'nacionalidade'=>'Checa'],
  	 	 	 ['id'=> 52, 'nacionalidade'=>'Dinamarquêsa'],
  	 	 	 ['id'=> 53, 'nacionalidade'=>'Djibouti'],
  	 	 	 ['id'=> 54, 'nacionalidade'=>'Dominicana'],
  	 	 	 ['id'=> 55, 'nacionalidade'=>'Holandêsa'],
  	 	 	 ['id'=> 56, 'nacionalidade'=>'Timorense'],
  	 	 	 ['id'=> 57, 'nacionalidade'=>'Equatoriana'],
  	 	 	 ['id'=> 58, 'nacionalidade'=>'Egípcia'],
  	 	 	 ['id'=> 59, 'nacionalidade'=>'Emirian'],
  	 	 	 ['id'=> 60, 'nacionalidade'=>'Guineense equatoriana'],
  	 	 	 ['id'=> 61, 'nacionalidade'=>'Eritreu'],
         ['id'=> 62, 'nacionalidade'=>'Eslovaca'],
         ['id'=> 63, 'nacionalidade'=>'Eslovena'],
         ['id'=> 64, 'nacionalidade'=>'Espanhola'],
  	 	 	 ['id'=> 65, 'nacionalidade'=>'Estoniana'],
  	 	 	 ['id'=> 66, 'nacionalidade'=>'Etíope'],
  	 	 	 ['id'=> 67, 'nacionalidade'=>'Fijiana'],
  	 	 	 ['id'=> 68, 'nacionalidade'=>'Filipina'],
  	 	 	 ['id'=> 69, 'nacionalidade'=>'Finlandêsa'],
  	 	 	 ['id'=> 70, 'nacionalidade'=>'Francesa'],
  	 	 	 ['id'=> 71, 'nacionalidade'=>'Gabonêsa'],
  	 	 	 ['id'=> 72, 'nacionalidade'=>'Gambiana'],
  	 	 	 ['id'=> 73, 'nacionalidade'=>'Georgiana'],
  	 	 	 ['id'=> 74, 'nacionalidade'=>'Ganêsa'],
  	 	 	 ['id'=> 75, 'nacionalidade'=>'Graga'],
  	 	 	 ['id'=> 76, 'nacionalidade'=>'Grenadiana'],
  	 	 	 ['id'=> 77, 'nacionalidade'=>'Guatemalteca'],
  	 	 	 ['id'=> 78, 'nacionalidade'=>'Guinea-Bissauan'],
  	 	 	 ['id'=> 79, 'nacionalidade'=>'Guinean'],
  	 	 	 ['id'=> 80, 'nacionalidade'=>'Guineense'],
         ['id'=> 81, 'nacionalidade'=>'Galêsa'],
  	 	 	 ['id'=> 82, 'nacionalidade'=>'Haitiana'],
  	 	 	 ['id'=> 83, 'nacionalidade'=>'Herzegoviniana'],
  	 	 	 ['id'=> 84, 'nacionalidade'=>'Hondurana'],
  	 	 	 ['id'=> 85, 'nacionalidade'=>'Hungariana'],
         ['id'=> 86, 'nacionalidade'=>'Iemenita'],
  	 	 	 ['id'=> 87, 'nacionalidade'=>'Islandês'],
  	 	 	 ['id'=> 88, 'nacionalidade'=>'Indiana'],
  	 	 	 ['id'=> 89, 'nacionalidade'=>'Indonesiana'],
  	 	 	 ['id'=> 90, 'nacionalidade'=>'Iraniana'],
  	 	 	 ['id'=> 91, 'nacionalidade'=>'Iraquiana'],
  	 	 	 ['id'=> 92, 'nacionalidade'=>'Irlandêsa'],
  	 	 	 ['id'=> 93, 'nacionalidade'=>'Israelense'],
  	 	 	 ['id'=> 94, 'nacionalidade'=>'Italiana'],
  	 	 	 ['id'=> 95, 'nacionalidade'=>'Jamaicana'],
  	 	 	 ['id'=> 96, 'nacionalidade'=>'Japonêsa'],
  	 	 	 ['id'=> 97, 'nacionalidade'=>'Jordaniana'],
  	 	 	 ['id'=> 98, 'nacionalidade'=>'Kittian and Nevisian'],
  	 	 	 ['id'=> 99, 'nacionalidade'=>'Kuwaitiana'],
  	 	 	 ['id'=> 100, 'nacionalidade'=>'Kyrgyz'],
  	 	 	 ['id'=> 101, 'nacionalidade'=>'Laosiana'],
  	 	 	 ['id'=> 102, 'nacionalidade'=>'Letã'],
  	 	 	 ['id'=> 103, 'nacionalidade'=>'Libanesa'],
  	 	 	 ['id'=> 104, 'nacionalidade'=>'Liberiana'],
  	 	 	 ['id'=> 105, 'nacionalidade'=>'Libanêsa'],
  	 	 	 ['id'=> 106, 'nacionalidade'=>'Liechtensteiner'],
  	 	 	 ['id'=> 107, 'nacionalidade'=>'Lituana'],
  	 	 	 ['id'=> 108, 'nacionalidade'=>'Luxemburguêsa'],
  	 	 	 ['id'=> 109, 'nacionalidade'=>'Macedônia'],
  	 	 	 ['id'=> 110, 'nacionalidade'=>'Malgaxe'],
  	 	 	 ['id'=> 111, 'nacionalidade'=>'Malawiana'],
  	 	 	 ['id'=> 112, 'nacionalidade'=>'Malaia'],
  	 	 	 ['id'=> 113, 'nacionalidade'=>'Maldiva'],
  	 	 	 ['id'=> 114, 'nacionalidade'=>'Maliana'],
  	 	 	 ['id'=> 115, 'nacionalidade'=>'Maltêsa'],
         ['id'=> 116, 'nacionalidade'=>'Marfinense'],
  	 	 	 ['id'=> 117, 'nacionalidade'=>'Marshallese'],
  	 	 	 ['id'=> 118, 'nacionalidade'=>'Mauritaniana'],
  	 	 	 ['id'=> 119, 'nacionalidade'=>'Mauritiana'],
  	 	 	 ['id'=> 120, 'nacionalidade'=>'Mexicana'],
  	 	 	 ['id'=> 121, 'nacionalidade'=>'Micronesiana'],
  	 	 	 ['id'=> 122, 'nacionalidade'=>'Moldava'],
  	 	 	 ['id'=> 123, 'nacionalidade'=>'Monacan'],
  	 	 	 ['id'=> 124, 'nacionalidade'=>'Mongol'],
  	 	 	 ['id'=> 125, 'nacionalidade'=>'Moroccan'],
  	 	 	 ['id'=> 126, 'nacionalidade'=>'Mosotho'],
  	 	 	 ['id'=> 127, 'nacionalidade'=>'Motswana'],
  	 	 	 ['id'=> 128, 'nacionalidade'=>'Mozambicana'],
  	 	 	 ['id'=> 129, 'nacionalidade'=>'Namibiana'],
  	 	 	 ['id'=> 130, 'nacionalidade'=>'Nauruan'],
  	 	 	 ['id'=> 131, 'nacionalidade'=>'Nepalese'],
  	 	 	 ['id'=> 132, 'nacionalidade'=>'Netherlander'],
  	 	 	 ['id'=> 133, 'nacionalidade'=>'Neozelandês'],
  	 	 	 ['id'=> 134, 'nacionalidade'=>'Ni-Vanuatu'],
  	 	 	 ['id'=> 135, 'nacionalidade'=>'Nicaragüense'],
  	 	 	 ['id'=> 136, 'nacionalidade'=>'Nigeriana'],
  	 	 	 ['id'=> 137, 'nacionalidade'=>'Norte Coreana'],
  	 	 	 ['id'=> 138, 'nacionalidade'=>'Norte Irlandêsa'],
  	 	 	 ['id'=> 139, 'nacionalidade'=>'Norueguêsa'],
  	 	 	 ['id'=> 140, 'nacionalidade'=>'Omani'],
  	 	 	 ['id'=> 141, 'nacionalidade'=>'Paquistanêsa'],
  	 	 	 ['id'=> 142, 'nacionalidade'=>'Palauan'],
  	 	 	 ['id'=> 143, 'nacionalidade'=>'Panamenha'],
  	 	 	 ['id'=> 144, 'nacionalidade'=>'Papua New Guinean'],
  	 	 	 ['id'=> 145, 'nacionalidade'=>'Paraguaia'],
  	 	 	 ['id'=> 146, 'nacionalidade'=>'Peruana'],
  	 	 	 ['id'=> 147, 'nacionalidade'=>'Polonêsa'],
  	 	 	 ['id'=> 148, 'nacionalidade'=>'Portuguesa'],
  	 	 	 ['id'=> 149, 'nacionalidade'=>'Qatari'],
         ['id'=> 150, 'nacionalidade'=>'Queniana'],
  	 	 	 ['id'=> 151, 'nacionalidade'=>'Romêna'],
  	 	 	 ['id'=> 152, 'nacionalidade'=>'Russa'],
  	 	 	 ['id'=> 153, 'nacionalidade'=>'Ruandêsa'],
  	 	 	 ['id'=> 154, 'nacionalidade'=>'Saint Lucian'],
  	 	 	 ['id'=> 155, 'nacionalidade'=>'Salvadoran'],
  	 	 	 ['id'=> 156, 'nacionalidade'=>'Samoan'],
  	 	 	 ['id'=> 157, 'nacionalidade'=>'San Marinese'],
  	 	 	 ['id'=> 158, 'nacionalidade'=>'Sao Tomean'],
  	 	 	 ['id'=> 159, 'nacionalidade'=>'Saudita'],
  	 	 	 ['id'=> 160, 'nacionalidade'=>'Escocêsa'],
  	 	 	 ['id'=> 161, 'nacionalidade'=>'Senegalesa'],
  	 	 	 ['id'=> 162, 'nacionalidade'=>'Servia'],
  	 	 	 ['id'=> 163, 'nacionalidade'=>'Seychellois'],
  	 	 	 ['id'=> 164, 'nacionalidade'=>'Sierra Leonean'],
  	 	 	 ['id'=> 165, 'nacionalidade'=>'Solomon Islander'],
  	 	 	 ['id'=> 166, 'nacionalidade'=>'Somali'],
  	 	 	 ['id'=> 167, 'nacionalidade'=>'Sul Africana'],
  	 	 	 ['id'=> 168, 'nacionalidade'=>'Sul Coreana'],
  	 	 	 ['id'=> 169, 'nacionalidade'=>'Sri Lankan'],
  	 	 	 ['id'=> 170, 'nacionalidade'=>'Sudanêsa'],
  	 	 	 ['id'=> 171, 'nacionalidade'=>'Surinamer'],
  	 	 	 ['id'=> 172, 'nacionalidade'=>'Swazi'],
  	 	 	 ['id'=> 173, 'nacionalidade'=>'Sueca'],
  	 	 	 ['id'=> 174, 'nacionalidade'=>'Suiça'],
  	 	 	 ['id'=> 175, 'nacionalidade'=>'Síria'],
  	 	 	 ['id'=> 176, 'nacionalidade'=>'Taiwanêsa'],
  	 	 	 ['id'=> 177, 'nacionalidade'=>'Tadjique'],
  	 	 	 ['id'=> 178, 'nacionalidade'=>'Tanzaniana'],
  	 	 	 ['id'=> 179, 'nacionalidade'=>'Tailandêsa'],
  	 	 	 ['id'=> 180, 'nacionalidade'=>'Togolêsa'],
  	 	 	 ['id'=> 181, 'nacionalidade'=>'Tonganêsa'],
  	 	 	 ['id'=> 182, 'nacionalidade'=>'Trinidadiano ou Tobagoniano'],
  	 	 	 ['id'=> 183, 'nacionalidade'=>'Tunisiana'],
  	 	 	 ['id'=> 184, 'nacionalidade'=>'Turca'],
  	 	 	 ['id'=> 185, 'nacionalidade'=>'Tuvaluan'],
  	 	 	 ['id'=> 186, 'nacionalidade'=>'Ugandan'],
  	 	 	 ['id'=> 187, 'nacionalidade'=>'Ucraniana'],
  	 	 	 ['id'=> 188, 'nacionalidade'=>'Uruguaia'],
  	 	 	 ['id'=> 189, 'nacionalidade'=>'Uzbequistã'],
  	 	 	 ['id'=> 190, 'nacionalidade'=>'Venezuelana'],
  	 	 	 ['id'=> 191, 'nacionalidade'=>'Vietnamita'],
  	 	 	 ['id'=> 192, 'nacionalidade'=>'Zambiana'],
  	 	 	 ['id'=> 193, 'nacionalidade'=>'Zimbabweana']
         
 	 	 ]);
    }

}
